dotfiles: ~/dotfiles/
notes: /Users/abel/Library/Mobile Documents/iCloud~md~obsidian/Documents/notes/
  # notes: ~/Obsidian/notes/
  # log: ~/Logseq/log/
  # german-notes: ~/Obsidian/german/  
german-notes: /Users/abel/Library/Mobile Documents/iCloud~md~obsidian/Documents/german-notes/
